Docs update
crewAIInc/crewAI pull request #1008
Opened 2024-07-26 04:36 UTC by theCyberTech

This PR implements the following to the CrewAI documentation

1. Created aa new section `getting started`
2. Moved the following to new section
     2a. `Start-a-New-CrewAI-Project.md`
     2b. `Installing-CrewAI.md`
3. Renamed `Start-a-New-CrewAI-Project.md` to `Start-a-New-CrewAI-Project-Template-Method`
4. updated `Start-a-New-CrewAI-Project-Template-Method.md` to include more detailed requisites & setup instructions
5. Small update to `Installing-CrewAI.md` to include alternative pip install
6. Updated Index.md to reflect changes
7. Deleted `Creating-a-Crew-and-kick-it-off.md` from how-to

2024-07-26 18:51 UTC, bhancockio requested changes

2024-07-26 18:51 UTC, bhancockio commented on docs/getting-started/Start-a-New-CrewAI-Project-Template-Method.md
> +2. The preferred way of setting up CrewAI is using the crewai create command.This will create a new project folder and install a skeleton template for you to work on.
Let's put `crewai create` in backticks.

2024-07-26 18:51 UTC, bhancockio commented on docs/getting-started/Start-a-New-CrewAI-Project-Template-Method.md
> +Now, to create a new CrewAIproject, run the following CLI command:
put a space before project.

2024-07-26 18:51 UTC, bhancockio commented on docs/index.md
> +                        <li><a href='./getting-started/Start-a-New-CrewAI-Project-Template-Method.md'>
Fix the HTML here to be formatted like the rest of the code.

2024-07-28 14:55 UTC, joaomdmoura approved these changes

2024-07-28 14:55 UTC, merged