restrict python version compatibility to <=3.12 due to pyo3 and tiktoken issues
crewAIInc/crewAI pull request #1704
Opened 2024-12-04 22:03 UTC by tanmaik

this pull request explicitly limits the supported python version to <=3.12 in the codebase. while python 3.13 is mentioned in the documentation as supported, the current dependencies—pyo3 (v0.20.3) and tiktoken—do not fully support it, leading to build failures. this change ensures clarity and prevents users from encountering compatibility issues until pyo3 and tiktoken are updated to support python 3.13.

updated python version constraints in [relevant file(s), e.g., pyproject.toml, setup.py].
added a note explaining the version restriction and its dependency on pyo3 and tiktoken.

users attempting to use python 3.13 encounter build errors due to version constraints in pyo3 and tiktoken. this update aligns the codebase with the currently supported versions, ensuring a smoother developer experience and preventing confusion.

2024-12-04 22:06 UTC, joaomdmoura commented
Disclaimer: This review was made by a crew of AI Agents.

# Code Review Comment for PR #1704 - Fix Compatibility Issue

## Overview
This pull request modifies Python version compatibility requirements, specifically removing support for Python 3.13 and maintaining compatibility with versions 3.10 through 3.12. These changes ensure stability and compatibility with the project's core dependencies.

## Code Quality Findings

### Configuration Files Changes

- **`pyproject.toml`**
  ```diff
  - requires-python = ">=3.10,<=3.13"
  + requires-python = ">=3.10,<=3.12"
  ```
  **Assessment**: This change is prudent as Python 3.13 is still in development. By limiting the supported versions to 3.12, we avoid potential issues stemming from the use of an unstable version.

- **`.github/workflows/tests.yml`**
  ```diff
  - run: uv python install 3.11.9
  + run: uv python install 3.12.2
  ```
  **Assessment**: Utilizing Python 3.12 instead of 3.11.9 for testing is a positive update, ensuring that our CI process leverages the most stable and recent Python version.

### Documentation Updates
Documentation has been revised across several files to reflect the new Python compatibility. This includes:
- `README.md`
- `docs/installation.mdx`
- Template README files in `src/crewai/cli/templates/`
  
**Consistency Check**: All documentation updates are consistent, which is essential for user clarity regarding the supported Python versions.

### Bug Report Template Update
- **`.github/ISSUE_TEMPLATE/bug_report.yml`**
  ```diff
  - '3.13'
  ```
  **Assessment**: Removing Python 3.13 from the bug report template is wise, reducing potential confusion for users encountering issues on unsupported versions.

## Recommendations

1. **Version Specification Enhancement**
   - It's advisable to add a comment in `pyproject.toml` to clarify the version constraint rationale:
     ```toml
     # Limited to Python 3.12 for stability and compatibility with core dependencies
     requires-python = ">=3.10,<=3.12"
     ```

2. **Documentation Enhancement**
   - A note should be included in the documentation to explain the rationale behind not supporting Python 3.13:
     ```markdown
     > **Note:** CrewAI currently supports Python versions 3.10 through 3.12. Python 3.13 will be supported once it reaches stable release status.
     ```

3. **Testing Matrix in CI**
   - Updating the GitHub Actions workflow to test against all supported Python versions could improve reliability:
     ```yaml
     strategy:
       matrix:
         python-version: ['3.10', '3.11', '3.12']
     steps:
       - name: Set up Python $
         run: uv python install $
     ```

## Security Implications
There are no security concerns identified in these changes. The version restrictions are a proactive measure to maintain stability within the project.

## Overall Assessment
✅ **LGTM (Looks Good To Merge)**
- Changes are consistent and well-documented.
- The project's documentation accurately reflects current compatibility requirements.
- Version constraints are suitable for ongoing production use.
- No breaking changes were introduced, ensuring a smooth transition for users.

## Follow-up Suggestions
1. Develop a version compatibility matrix within the documentation to aid users in understanding version support.
2. Consider implementing automated tests to validate compatibility across all supported Python versions.
3. Establish a roadmap for future Python version support to guide both contributors and users.

The changes introduced in this PR are well-structured, and the decision to remove support for Python 3.13 appears sound in light of the goal of maintaining stability. This proactive approach will help to avoid introducing potential issues in production environments.

2024-12-05 15:06 UTC, bhancockio commented
This is beautiful! We just talked about adding in this fix yesterday internally.

Thank you so much for doing this @tanmaik!!

2024-12-05 15:09 UTC, bhancockio approved these changes

2024-12-05 15:16 UTC, bhancockio requested changes

2024-12-05 15:16 UTC, bhancockio commented on .github/workflows/tests.yml
> +        run: uv python install 3.12.2
Can you please change this to 3.12.8?

Something a few test are behaving weird on 3.12.2?

2024-12-05 17:19 UTC, bhancockio approved these changes

2024-12-07 19:53 UTC, tanmaik commented
@tonykipkemboi

2024-12-09 15:27 UTC, tonykipkemboi approved these changes
LGTM

2024-12-09 16:32 UTC, tanmaik commented
ready to merge?

2024-12-09 19:07 UTC, closed without merging